### ISSUE TITLE
Toolbar button misbehaviour

### ISSUE THREAD

**Issue by MichiFr** [Rookiestyle/KPColorChange#1]
## Overview
Minor issus with this plugin, using Keepass 2.46. KPColorChange version 2.1.2.
Using the toolbar button to hide expired accounts not always working properly.

## Steps to Reproduce
1. Open a database with expired accounts.
2. KP focuses in a folder with one or more expired accounts (don't know it this is a prerequisite). The folder that was selected when closing a previous database.
3. Clicking on the KPcolorChange toolbar button to **unhide** expired accounts, which immediately shows expired items in the account list.
4. Clicking a **second** time on the same button, those previously revealed accounts still show up in the list.
5. When switching to a different folder and return to the previously folder, those exp. accounts are again hidden and the button works correctly now and for each subsequent clicks.

Would you pls. check and fix if it is a bug in your plugin?

Thanks!
Michael

**Comment by Rookiestyle** [comment]
I can't reproduce that.
My test setup:
1 group with 5 entries. 1 expired, 2 expiring in 7 days, 2 expiring in 7 weeks
At startup, KeePass displays this group, the one expired entry is hidden
Clicking the toolbar button shows the entry
Clicking the toolbar button again hides the entry

Please attach a debugfile, it will hopefully help me analyzing this topic, you need to rename the file from .xml to .txt to be able to attach it
https://github.com/Rookiestyle/KPColorChange/wiki/Create-a-debugfile#startup-parameter describes how to do that (*startup parameter* approach)

Do you have "Show expired entries (if any)" active in KeePass options?

**Comment by MichiFr** [comment]
Thanks for your reply and sorry to hear that you cannot reproduce the behaviour. Nevertheless, I've created a debug file and attached it to my answer.

1) I've used the same approach as described above.
2) The database opens automatically when starting Keepass, since I've added the database file as a parameter. Additionally, I've now use the option -debugplugin:kpcolorchange, so the command line looks as follows: 
`\\192.168.6.97\Portable\Keepass\KeePass.exe -debugplugin:kpcolorchange \\isar\webdav\pw.kdbx`
3) I then performed the very same steps as already noted above and again noticed the same behaviour.
4) I closed Keepass and located the debug file to attach it here.

Regarding your question: No, I'm not using the option "Show expired entries (if any)" in section "After Opening a Database".

FWIW, the default shortcut "Ctrl+Shift+H" does not work either at the time the toolbar button fails. If changing this shortcut to a custom one, the button does not work either.

cu,
Michael
[Debug_KPColorChange_20201128T103640Z.txt](https://github.com/Rookiestyle/KPColorChange/files/5610440/Debug_KPColorChange_20201128T103640Z.txt)

**Comment by Rookiestyle** [comment]
I managed to reproduce it, but it involves minimizing KeePass to the tray inbetween your initial steps 3 and 4 which I understood you don't do.

Nevertheless, please give it a try: https://github.com/Rookiestyle/KPColorChange/releases/tag/v2.1.2.1

**Comment by MichiFr** [comment]
Yeah! This release seems to have fixed the issue I've reported! Thanks for fixing!

**Edit**: Maybe worth looking into, too: prerequisite is that the toolbar button indicates that expired items are hidden as expected, which is correct while browsing the account in my database. 

When searching for items, using Ctrl + F, expired items are still found. The general option for "Exclude expired items in quick search" is active. This should not count here, because I'm using the popup and not the toolbar search.

Michael

**Comment by Rookiestyle** [comment]
Thanks for testing the solution to the initial issue.

When searching for items using Ctrl + F, there is a KeePass standard checkbox labelled "Exclude expired entried".
KPColorChange respects this checkbox setting which can be different from "Exclude expired items in quick search".

If you have ticked this checkbox in the "Find" and expired entries are still shown, please create a new issue and attach a debugfile.
