### ISSUE TITLE
Change background color of the group too

### ISSUE THREAD

**Issue by JackySw** [Rookiestyle/KPColorChange#5]
Thanks for this nice plugin.

What would be nice if the backgroundcolor of the group where the expired entry is in, would change too. With a lot of groups, this would be very handy! Any idea if this could be implemented, would this be a lot of work?

**Comment by Rookiestyle** [comment]
I tried but this is not possible.
Even if it was possible, it would require to check entries in subgroups as well which would be to "expensive".
